name: Feature / Fix branch
on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - main

jobs:
  python-ci:
    uses: ./.github/workflows/python-ci.yml
    secrets: inherit